/* よく受験される資格・検定のプリセット。
   名前を入力すると候補が出て、選ぶとカテゴリ・目標スコアなどが自動入力されます。
   targetScore は「合格ライン相当」の目安です。受験料や合格基準は変更されることがあるので、
   必ず公式サイトで最新の情報を確認してください。 */
window.CERT_PRESETS = [

  /* ---------- 語学 ---------- */
  { name: 'TOEIC L&R', alias: 'toeic とーいっく 英語 リスニング リーディング', category: '語学',
    scoreType: 'score', targetScore: 800, maxScore: 990, scoreUnit: '点', fee: 7810,
    url: 'https://www.iibc-global.org/toeic.html', memo: '合否ではなくスコアで評価。' },
  { name: 'TOEIC S&W', alias: 'toeic speaking writing スピーキング ライティング 英語', category: '語学',
    scoreType: 'score', targetScore: 300, maxScore: 400, scoreUnit: '点',
    url: 'https://www.iibc-global.org/toeic.html' },
  { name: 'TOEFL iBT', alias: 'toefl とーふる 英語 留学', category: '語学',
    scoreType: 'score', targetScore: 80, maxScore: 120, scoreUnit: '点',
    url: 'https://www.ets.org/toefl.html', memo: '4技能各30点、合計120点満点。' },
  { name: 'IELTS アカデミック', alias: 'ielts あいえるつ 英語 留学', category: '語学',
    scoreType: 'score', targetScore: 6.5, maxScore: 9, scoreUnit: 'バンド',
    url: 'https://www.eiken.or.jp/ielts/' },
  { name: '実用英語技能検定 1級', alias: '英検 えいけん eiken 1級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: '実用英語技能検定 準1級', alias: '英検 えいけん eiken 準1級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: '実用英語技能検定 2級', alias: '英検 えいけん eiken 2級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: '実用英語技能検定 準2級', alias: '英検 えいけん eiken 準2級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: 'HSK 5級', alias: 'hsk 中国語 ちゅうごくご', category: '語学',
    scoreType: 'score', targetScore: 180, maxScore: 300, scoreUnit: '点',
    url: 'https://www.hsk.jp/' },
  { name: '中国語検定 2級', alias: '中検 ちゅうけん 中国語', category: '語学',
    scoreType: 'pass', url: 'https://www.chuken.gr.jp/' },
  { name: '韓国語能力試験 TOPIK II', alias: 'topik とぴっく 韓国語 かんこくご', category: '語学',
    scoreType: 'score', targetScore: 190, maxScore: 300, scoreUnit: '点',
    url: 'https://www.kref.or.jp/examination', memo: '取得級は総得点で決まる（3級〜6級）。' },
  { name: '実用フランス語技能検定 2級', alias: '仏検 ふつけん フランス語', category: '語学',
    scoreType: 'pass', url: 'https://apefdapf.org/' },
  { name: 'ドイツ語技能検定 2級', alias: '独検 どっけん ドイツ語', category: '語学',
    scoreType: 'pass', url: 'https://www.dokken.or.jp/' },
  { name: '全国通訳案内士', alias: 'つうやくあんないし 通訳 ガイド 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.jnto.go.jp/projects/visitor-support/interpreter-guide-exams.html' },

  /* ---------- IT ---------- */
  { name: 'ITパスポート試験', alias: 'iパス itパスポート ip 情報処理', category: 'IT',
    scoreType: 'score', targetScore: 600, maxScore: 1000, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/ip.html', memo: '総合600点以上かつ分野別各300点以上で合格。' },
  { name: '情報セキュリティマネジメント試験', alias: 'sg セキュマネ 情報処理 セキュリティ', category: 'IT',
    scoreType: 'score', targetScore: 600, maxScore: 1000, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sg.html' },
  { name: '基本情報技術者試験', alias: 'fe kihon きほんじょうほう 基本情報 情報処理', category: 'IT',
    scoreType: 'score', targetScore: 600, maxScore: 1000, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/fe.html', memo: '科目A・科目Bとも600点以上で合格。' },
  { name: '応用情報技術者試験', alias: 'ap oyo おうようじょうほう 応用情報 情報処理', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/ap.html', memo: '午前・午後とも60点以上で合格。' },
  { name: '情報処理安全確保支援士試験', alias: 'sc 登録セキスペ セキュリティ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sc.html' },
  { name: 'ネットワークスペシャリスト試験', alias: 'nw ネスペ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/nw.html' },
  { name: 'データベーススペシャリスト試験', alias: 'db デスペ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/db.html' },
  { name: 'プロジェクトマネージャ試験', alias: 'pm プロマネ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/pm.html' },
  { name: 'システムアーキテクト試験', alias: 'sa 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sa.html' },
  { name: 'ITストラテジスト試験', alias: 'st 情報処理 高度 ストラテジ', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/st.html' },
  { name: 'エンベデッドシステムスペシャリスト試験', alias: 'es 組込み 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/es.html' },
  { name: 'ITサービスマネージャ試験', alias: 'sm 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sm.html' },
  { name: 'システム監査技術者試験', alias: 'au かんさ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/au.html' },
  { name: 'AWS認定 クラウドプラクティショナー', alias: 'aws clf クラウド amazon', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://aws.amazon.com/jp/certification/certified-cloud-practitioner/' },
  { name: 'AWS認定 ソリューションアーキテクト アソシエイト', alias: 'aws saa クラウド amazon', category: 'IT',
    scoreType: 'score', targetScore: 720, maxScore: 1000, scoreUnit: '点',
    url: 'https://aws.amazon.com/jp/certification/certified-solutions-architect-associate/' },
  { name: 'Microsoft Azure Fundamentals (AZ-900)', alias: 'azure az900 マイクロソフト クラウド', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-fundamentals/' },
  { name: 'Google Cloud Associate Cloud Engineer', alias: 'gcp google cloud ace クラウド', category: 'IT',
    scoreType: 'pass', url: 'https://cloud.google.com/learn/certification/cloud-engineer' },
  { name: 'LinuC レベル1', alias: 'linuc りなっく linux リナックス', category: 'IT',
    scoreType: 'score', targetScore: 480, maxScore: 800, scoreUnit: '点',
    url: 'https://linuc.org/' },
  { name: 'LPIC-1', alias: 'lpic linux リナックス', category: 'IT',
    scoreType: 'score', targetScore: 500, maxScore: 800, scoreUnit: '点',
    url: 'https://www.lpi.org/ja/our-certifications/lpic-1-overview/' },
  { name: 'CCNA', alias: 'ccna cisco シスコ ネットワーク', category: 'IT',
    scoreType: 'pass', url: 'https://www.cisco.com/site/jp/ja/learn/training-certifications/certifications/enterprise/ccna/index.html' },
  { name: 'Oracle Master Bronze DBA', alias: 'oracle オラクル ブロンズ データベース', category: 'IT',
    scoreType: 'pass', url: 'https://www.oracle.com/jp/education/certification/' },
  { name: 'Python3 エンジニア認定基礎試験', alias: 'python ぱいそん プログラミング', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://www.pythonic-exam.com/' },
  { name: 'G検定（JDLA Deep Learning for GENERAL）', alias: 'g検定 jdla ai ディープラーニング 機械学習', category: 'IT',
    scoreType: 'pass', url: 'https://www.jdla.org/certificate/general/' },
  { name: 'E資格（JDLA Deep Learning for ENGINEER）', alias: 'e資格 jdla ai ディープラーニング 機械学習', category: 'IT',
    scoreType: 'pass', url: 'https://www.jdla.org/certificate/engineer/' },
  { name: '統計検定 2級', alias: 'toukei とうけい 統計 データ分析', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.toukei-kentei.jp/' },
  { name: 'CompTIA Security+', alias: 'comptia security セキュリティ', category: 'IT',
    scoreType: 'score', targetScore: 750, maxScore: 900, scoreUnit: '点',
    url: 'https://www.comptia.jp/' },
  { name: 'MOS Excel 一般（アソシエイト）', alias: 'mos excel エクセル マイクロソフト オフィス', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://mos.odyssey-com.co.jp/' },
  { name: 'ITIL 4 ファンデーション', alias: 'itil いちる サービスマネジメント', category: 'IT',
    scoreType: 'score', targetScore: 65, maxScore: 100, scoreUnit: '%',
    url: 'https://www.peoplecert.org/ja/' },

  /* ---------- 会計・金融 ---------- */
  { name: '日商簿記3級', alias: 'boki ぼき 簿記 日商 3級 会計', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 3300,
    url: 'https://www.kentei.ne.jp/bookkeeping' },
  { name: '日商簿記2級', alias: 'boki ぼき 簿記 日商 2級 会計', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 5500,
    url: 'https://www.kentei.ne.jp/bookkeeping' },
  { name: '日商簿記1級', alias: 'boki ぼき 簿記 日商 1級 会計', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 8800,
    url: 'https://www.kentei.ne.jp/bookkeeping', memo: '1科目でも40%未満があると不合格。' },
  { name: 'FP技能検定3級', alias: 'fp ファイナンシャルプランナー 3級 お金', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.jafp.or.jp/exam/', memo: '学科・実技それぞれ6割以上で合格。' },
  { name: 'FP技能検定2級', alias: 'fp ファイナンシャルプランナー 2級 お金', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.jafp.or.jp/exam/', memo: '学科・実技それぞれ6割以上で合格。' },
  { name: 'FP技能検定1級', alias: 'fp ファイナンシャルプランナー 1級 お金', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.jafp.or.jp/exam/' },
  { name: '証券外務員一種', alias: 'がいむいん 証券 金融', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '%',
    url: 'https://www.jsda.or.jp/gaimuin/' },
  { name: '中小企業診断士', alias: 'shindanshi しんだんし 診断士 経営 コンサル', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.j-smeca.jp/' },
  { name: '公認会計士', alias: 'kaikeishi かいけいし 会計士 cpa', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.fsa.go.jp/cpaaob/' },
  { name: '税理士', alias: 'zeirishi ぜいりし 税理士 税務', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.nta.go.jp/taxes/zeirishi/zeirishishiken/', memo: '科目合格制。5科目合格で官報合格。' },
  { name: 'USCPA（米国公認会計士）', alias: 'uscpa 米国公認会計士 会計 英語', category: '会計・金融',
    scoreType: 'score', targetScore: 75, maxScore: 99, scoreUnit: '点',
    url: 'https://nasba.org/' },
  { name: 'ビジネス会計検定2級', alias: 'びじねすかいけい 会計 財務諸表', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.b-accounting.jp/' },

  /* ---------- 法律 ---------- */
  { name: '行政書士', alias: 'gyosei ぎょうせいしょし 行書 法律', category: '法律',
    scoreType: 'score', targetScore: 180, maxScore: 300, scoreUnit: '点',
    url: 'https://gyosei-shiken.or.jp/', memo: '法令等・一般知識それぞれに足切りあり。' },
  { name: '司法書士', alias: 'shoshi しほうしょし 法律 登記', category: '法律',
    scoreType: 'pass', url: 'https://www.moj.go.jp/shikaku_saiyo_index2.html' },
  { name: '社会保険労務士', alias: 'sharoshi しゃろうし 社労士 労務 年金', category: '法律',
    scoreType: 'pass', url: 'https://www.sharosi-siken.or.jp/' },
  { name: '弁理士', alias: 'べんりし 特許 知財', category: '法律',
    scoreType: 'pass', url: 'https://www.jpo.go.jp/news/benrishi/' },
  { name: '司法試験予備試験', alias: 'よびしけん 司法試験 法律', category: '法律',
    scoreType: 'pass', url: 'https://www.moj.go.jp/jinji/shihoushiken/' },
  { name: 'ビジネス実務法務検定2級', alias: 'ほうむけんてい ビジ法 法律', category: '法律',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.kentei.org/houmu/' },
  { name: 'ビジネス実務法務検定3級', alias: 'ほうむけんてい ビジ法 法律', category: '法律',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.kentei.org/houmu/' },
  { name: '知的財産管理技能検定2級', alias: 'ちざい 知財 特許 商標', category: '法律',
    scoreType: 'pass', url: 'https://www.kentei-info-ip-edu.org/', memo: '学科・実技それぞれ80%以上で合格。' },
  { name: '個人情報保護士', alias: 'こじんじょうほう プライバシー セキュリティ', category: '法律',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '%',
    url: 'https://www.joho-gakushu.or.jp/piip/' },

  /* ---------- 不動産・建築 ---------- */
  { name: '宅地建物取引士', alias: 'takken たっけん 宅建 宅建士 不動産', category: '不動産・建築',
    scoreType: 'score', targetScore: 38, maxScore: 50, scoreUnit: '点', fee: 8200,
    url: 'https://www.retio.or.jp/exam/', memo: '合格ラインは相対評価で毎年変動（おおむね35点前後）。' },
  { name: '賃貸不動産経営管理士', alias: 'ちんかん 賃管 不動産 賃貸', category: '不動産・建築',
    scoreType: 'score', targetScore: 36, maxScore: 50, scoreUnit: '点',
    url: 'https://www.chintaikanrishi.jp/' },
  { name: 'マンション管理士', alias: 'マン管 まんかん 不動産 管理', category: '不動産・建築',
    scoreType: 'score', targetScore: 38, maxScore: 50, scoreUnit: '点',
    url: 'https://www.mankan.org/' },
  { name: '管理業務主任者', alias: 'かんぎょう 管業 不動産 管理', category: '不動産・建築',
    scoreType: 'score', targetScore: 36, maxScore: 50, scoreUnit: '点',
    url: 'https://www.kanrikyo.or.jp/' },
  { name: '二級建築士', alias: 'けんちくし 建築 二級', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.jaeic.or.jp/' },
  { name: '一級建築士', alias: 'けんちくし 建築 一級', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.jaeic.or.jp/' },
  { name: '土地家屋調査士', alias: 'ちょうさし 調査士 測量 不動産', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.moj.go.jp/shikaku_saiyo_index3.html' },
  { name: 'インテリアコーディネーター', alias: 'インテリア コーディネーター 住宅', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.interior.or.jp/' },

  /* ---------- 技術・工業 ---------- */
  { name: '危険物取扱者 乙種第4類', alias: 'kikenbutsu きけんぶつ 乙4 おつよん 危険物', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.shoubo-shiken.or.jp/', memo: '3科目それぞれ60%以上で合格。' },
  { name: '第二種電気工事士', alias: 'denko でんこう 電工二種 電気 工事', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.shiken.or.jp/', memo: '学科試験合格後に技能試験あり。' },
  { name: '第一種電気工事士', alias: 'denko でんこう 電工一種 電気 工事', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.shiken.or.jp/' },
  { name: '第三種電気主任技術者（電験三種）', alias: 'denken でんけん 電験三種 電気 主任技術者', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.shiken.or.jp/', memo: '4科目それぞれ60点以上。科目合格制。' },
  { name: '消防設備士 乙種第6類', alias: 'しょうぼう 乙6 消火器 消防', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.shoubo-shiken.or.jp/' },
  { name: 'エネルギー管理士', alias: 'エネ管 えねかん 省エネ', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.eccj.or.jp/' },
  { name: '第一種衛生管理者', alias: 'えいせいかんりしゃ 衛生 労働安全', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.exam.or.jp/', memo: '総得点60%以上かつ各科目40%以上。' },
  { name: 'QC検定2級', alias: 'qc 品質管理 ひんしつ', category: '技術・工業',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '%',
    url: 'https://webdesk.jsa.or.jp/common/W10K0500/index/qc/' },
  { name: '技術士第一次試験', alias: 'ぎじゅつし 技術士 jabee', category: '技術・工業',
    scoreType: 'score', targetScore: 50, maxScore: 100, scoreUnit: '%',
    url: 'https://www.engineer.or.jp/' },
  { name: '実用数学技能検定（数検）準1級', alias: 'suken すうけん 数検 数学', category: '技術・工業',
    scoreType: 'pass', url: 'https://www.su-gaku.net/' },

  /* ---------- 医療・福祉 ---------- */
  { name: '登録販売者', alias: 'とうろくはんばいしゃ 医薬品 ドラッグストア', category: '医療・福祉',
    scoreType: 'score', targetScore: 84, maxScore: 120, scoreUnit: '点',
    url: 'https://www.mhlw.go.jp/', memo: '総得点70%以上かつ各章35〜40%以上（都道府県により異なる）。' },
  { name: '介護福祉士', alias: 'kaigo かいごふくしし 介護 福祉', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.sssc.or.jp/kaigo/' },
  { name: '社会福祉士', alias: 'しゃかいふくしし 福祉 ソーシャルワーカー', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.sssc.or.jp/shakai/' },
  { name: '精神保健福祉士', alias: 'せいしんほけんふくしし 福祉 メンタル', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.sssc.or.jp/seishin/' },
  { name: '保育士', alias: 'hoikushi ほいくし 保育 こども', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.hoyokyo.or.jp/exam/', memo: '筆記は各科目6割以上。科目合格は3年有効。' },
  { name: '看護師国家試験', alias: 'kangoshi かんごし 看護 医療', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.mhlw.go.jp/kouseiroudoushou/shikaku_shiken/kangoshi/' },
  { name: '公認心理師', alias: 'こうにんしんりし 心理 カウンセラー', category: '医療・福祉',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000116049.html' },

  /* ---------- ビジネス・一般 ---------- */
  { name: '秘書検定2級', alias: 'hisho ひしょけんてい 秘書 ビジネスマナー', category: 'ビジネス',
    scoreType: 'pass', url: 'https://jitsumu-kentei.jp/HS/index', memo: '理論・実技それぞれ60%以上で合格。' },
  { name: '秘書検定準1級', alias: 'hisho ひしょけんてい 秘書 ビジネスマナー', category: 'ビジネス',
    scoreType: 'pass', url: 'https://jitsumu-kentei.jp/HS/index' },
  { name: 'リテールマーケティング（販売士）2級', alias: 'はんばいし 販売士 リテール 小売', category: 'ビジネス',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.kentei.ne.jp/retailsales' },
  { name: '国内旅行業務取扱管理者', alias: 'りょこうぎょうむ 旅行 国内 ツアー', category: 'ビジネス',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.anta.or.jp/' },
  { name: '総合旅行業務取扱管理者', alias: 'りょこうぎょうむ 旅行 総合 海外 ツアー', category: 'ビジネス',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.jata-net.or.jp/' },
  { name: '通関士', alias: 'つうかんし 通関 貿易', category: 'ビジネス',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.customs.go.jp/tsukanshi/' },
  { name: '日本漢字能力検定 2級', alias: 'kanken かんけん 漢検 漢字', category: 'その他',
    scoreType: 'score', targetScore: 160, maxScore: 200, scoreUnit: '点',
    url: 'https://www.kanken.or.jp/kanken/', memo: '80%程度で合格。' },
  { name: '気象予報士', alias: 'kisho きしょうよほうし 天気 気象', category: 'その他',
    scoreType: 'pass', url: 'https://www.jmbsc.or.jp/jp/examination/examination.html' },
  { name: '普通自動車第一種運転免許', alias: 'menkyo うんてんめんきょ 車 免許 普通免許', category: '車・運転',
    scoreType: 'pass', memo: '学科90点以上／100点満点。' },
  { name: '普通自動二輪免許', alias: 'ばいく バイク 二輪 免許', category: '車・運転',
    scoreType: 'pass' },
  { name: '大型自動二輪免許', alias: 'ばいく バイク 大型二輪 免許', category: '車・運転',
    scoreType: 'pass' },
  { name: '国家公務員一般職試験（大卒程度）', alias: 'こうむいん 公務員 国家一般職', category: '公務員・教育',
    scoreType: 'pass', url: 'https://www.jinji.go.jp/saiyo/saiyo.html' },
  { name: '地方公務員上級（都道府県・政令市）', alias: 'こうむいん 公務員 地方上級', category: '公務員・教育',
    scoreType: 'pass' },
  { name: '教員採用試験', alias: 'きょういん 教員 教採 先生', category: '公務員・教育',
    scoreType: 'pass' },
];
