/* よく受験される資格・検定のプリセット。
   名前を入力すると候補が出て、選ぶとカテゴリ・目標スコアなどが自動入力されます。
   targetScore は「合格ライン相当」の目安です。受験料や合格基準は変更されることがあるので、
   必ず公式サイトで最新の情報を確認してください。 */
window.CERT_PRESETS = [

  /* ---------- 語学 ---------- */
  { name: 'TOEIC L&R', alias: 'toeic とーいっく 英語 リスニング リーディング', category: '語学',
    scoreType: 'score', targetScore: 800, maxScore: 990, scoreUnit: '点', fee: 7810,
    url: 'https://www.iibc-global.org/toeic.html', memo: '合否ではなくスコアで評価。' },
  { name: 'TOEIC S&W', alias: 'toeic speaking writing スピーキング ライティング 英語', category: '語学',
    scoreType: 'score', targetScore: 300, maxScore: 400, scoreUnit: '点',
    url: 'https://www.iibc-global.org/toeic.html' },
  { name: 'TOEFL iBT', alias: 'toefl とーふる 英語 留学', category: '語学',
    scoreType: 'score', targetScore: 80, maxScore: 120, scoreUnit: '点',
    url: 'https://www.ets.org/toefl.html', memo: '4技能各30点、合計120点満点。' },
  { name: 'IELTS アカデミック', alias: 'ielts あいえるつ 英語 留学', category: '語学',
    scoreType: 'score', targetScore: 6.5, maxScore: 9, scoreUnit: 'バンド',
    url: 'https://www.eiken.or.jp/ielts/' },
  { name: '実用英語技能検定 1級', alias: '英検 えいけん eiken 1級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: '実用英語技能検定 準1級', alias: '英検 えいけん eiken 準1級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: '実用英語技能検定 2級', alias: '英検 えいけん eiken 2級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: '実用英語技能検定 準2級', alias: '英検 えいけん eiken 準2級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: 'HSK 5級', alias: 'hsk 中国語 ちゅうごくご', category: '語学',
    scoreType: 'score', targetScore: 180, maxScore: 300, scoreUnit: '点',
    url: 'https://www.hsk.jp/' },
  { name: '中国語検定 2級', alias: '中検 ちゅうけん 中国語', category: '語学',
    scoreType: 'pass', url: 'https://www.chuken.gr.jp/' },
  { name: '韓国語能力試験 TOPIK II', alias: 'topik とぴっく 韓国語 かんこくご', category: '語学',
    scoreType: 'score', targetScore: 190, maxScore: 300, scoreUnit: '点',
    url: 'https://www.kref.or.jp/examination', memo: '取得級は総得点で決まる（3級〜6級）。' },
  { name: '実用フランス語技能検定 2級', alias: '仏検 ふつけん フランス語', category: '語学',
    scoreType: 'pass', url: 'https://apefdapf.org/' },
  { name: 'ドイツ語技能検定 2級', alias: '独検 どっけん ドイツ語', category: '語学',
    scoreType: 'pass', url: 'https://www.dokken.or.jp/' },
  { name: '全国通訳案内士', alias: 'つうやくあんないし 通訳 ガイド 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.jnto.go.jp/projects/visitor-support/interpreter-guide-exams.html' },

  /* ---------- IT ---------- */
  { name: 'ITパスポート試験', alias: 'iパス itパスポート ip 情報処理', category: 'IT',
    scoreType: 'score', targetScore: 600, maxScore: 1000, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/ip.html', memo: '総合600点以上かつ分野別各300点以上で合格。' },
  { name: '情報セキュリティマネジメント試験', alias: 'sg セキュマネ 情報処理 セキュリティ', category: 'IT',
    scoreType: 'score', targetScore: 600, maxScore: 1000, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sg.html' },
  { name: '基本情報技術者試験', alias: 'fe kihon きほんじょうほう 基本情報 情報処理', category: 'IT',
    scoreType: 'score', targetScore: 600, maxScore: 1000, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/fe.html', memo: '科目A・科目Bとも600点以上で合格。' },
  { name: '応用情報技術者試験', alias: 'ap oyo おうようじょうほう 応用情報 情報処理', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/ap.html', memo: '午前・午後とも60点以上で合格。' },
  { name: '情報処理安全確保支援士試験', alias: 'sc 登録セキスペ セキュリティ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sc.html' },
  { name: 'ネットワークスペシャリスト試験', alias: 'nw ネスペ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/nw.html' },
  { name: 'データベーススペシャリスト試験', alias: 'db デスペ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/db.html' },
  { name: 'プロジェクトマネージャ試験', alias: 'pm プロマネ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/pm.html' },
  { name: 'システムアーキテクト試験', alias: 'sa 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sa.html' },
  { name: 'ITストラテジスト試験', alias: 'st 情報処理 高度 ストラテジ', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/st.html' },
  { name: 'エンベデッドシステムスペシャリスト試験', alias: 'es 組込み 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/es.html' },
  { name: 'ITサービスマネージャ試験', alias: 'sm 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/sm.html' },
  { name: 'システム監査技術者試験', alias: 'au かんさ 情報処理 高度', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7500,
    url: 'https://www.ipa.go.jp/shiken/kubun/au.html' },
  { name: 'AWS認定 クラウドプラクティショナー', alias: 'aws clf クラウド amazon', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://aws.amazon.com/jp/certification/certified-cloud-practitioner/' },
  { name: 'AWS認定 ソリューションアーキテクト アソシエイト', alias: 'aws saa クラウド amazon', category: 'IT',
    scoreType: 'score', targetScore: 720, maxScore: 1000, scoreUnit: '点',
    url: 'https://aws.amazon.com/jp/certification/certified-solutions-architect-associate/' },
  { name: 'Microsoft Azure Fundamentals (AZ-900)', alias: 'azure az900 マイクロソフト クラウド', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://learn.microsoft.com/ja-jp/credentials/certifications/azure-fundamentals/' },
  { name: 'Google Cloud Associate Cloud Engineer', alias: 'gcp google cloud ace クラウド', category: 'IT',
    scoreType: 'pass', url: 'https://cloud.google.com/learn/certification/cloud-engineer' },
  { name: 'LinuC レベル1', alias: 'linuc りなっく linux リナックス', category: 'IT',
    scoreType: 'score', targetScore: 480, maxScore: 800, scoreUnit: '点',
    url: 'https://linuc.org/' },
  { name: 'LPIC-1', alias: 'lpic linux リナックス', category: 'IT',
    scoreType: 'score', targetScore: 500, maxScore: 800, scoreUnit: '点',
    url: 'https://www.lpi.org/ja/our-certifications/lpic-1-overview/' },
  { name: 'CCNA', alias: 'ccna cisco シスコ ネットワーク', category: 'IT',
    scoreType: 'pass', url: 'https://www.cisco.com/site/jp/ja/learn/training-certifications/certifications/enterprise/ccna/index.html' },
  { name: 'Oracle Master Bronze DBA', alias: 'oracle オラクル ブロンズ データベース', category: 'IT',
    scoreType: 'pass', url: 'https://www.oracle.com/jp/education/certification/' },
  { name: 'Python3 エンジニア認定基礎試験', alias: 'python ぱいそん プログラミング', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://www.pythonic-exam.com/' },
  { name: 'G検定（JDLA Deep Learning for GENERAL）', alias: 'g検定 jdla ai ディープラーニング 機械学習', category: 'IT',
    scoreType: 'pass', url: 'https://www.jdla.org/certificate/general/' },
  { name: 'E資格（JDLA Deep Learning for ENGINEER）', alias: 'e資格 jdla ai ディープラーニング 機械学習', category: 'IT',
    scoreType: 'pass', url: 'https://www.jdla.org/certificate/engineer/' },
  { name: '統計検定 2級', alias: 'toukei とうけい 統計 データ分析', category: 'IT',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.toukei-kentei.jp/' },
  { name: 'CompTIA Security+', alias: 'comptia security セキュリティ', category: 'IT',
    scoreType: 'score', targetScore: 750, maxScore: 900, scoreUnit: '点',
    url: 'https://www.comptia.jp/' },
  { name: 'MOS Excel 一般（アソシエイト）', alias: 'mos excel エクセル マイクロソフト オフィス', category: 'IT',
    scoreType: 'score', targetScore: 700, maxScore: 1000, scoreUnit: '点',
    url: 'https://mos.odyssey-com.co.jp/' },
  { name: 'ITIL 4 ファンデーション', alias: 'itil いちる サービスマネジメント', category: 'IT',
    scoreType: 'score', targetScore: 65, maxScore: 100, scoreUnit: '%',
    url: 'https://www.peoplecert.org/ja/' },

  /* ---------- 会計・金融 ---------- */
  { name: '日商簿記3級', alias: 'boki ぼき 簿記 日商 3級 会計', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 3300,
    url: 'https://www.kentei.ne.jp/bookkeeping' },
  { name: '日商簿記2級', alias: 'boki ぼき 簿記 日商 2級 会計', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 5500,
    url: 'https://www.kentei.ne.jp/bookkeeping' },
  { name: '日商簿記1級', alias: 'boki ぼき 簿記 日商 1級 会計', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 8800,
    url: 'https://www.kentei.ne.jp/bookkeeping', memo: '1科目でも40%未満があると不合格。' },
  { name: 'FP技能検定3級', alias: 'fp ファイナンシャルプランナー 3級 お金', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.jafp.or.jp/exam/', memo: '学科・実技それぞれ6割以上で合格。' },
  { name: 'FP技能検定2級', alias: 'fp ファイナンシャルプランナー 2級 お金', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.jafp.or.jp/exam/', memo: '学科・実技それぞれ6割以上で合格。' },
  { name: 'FP技能検定1級', alias: 'fp ファイナンシャルプランナー 1級 お金', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.jafp.or.jp/exam/' },
  { name: '証券外務員一種', alias: 'がいむいん 証券 金融', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '%',
    url: 'https://www.jsda.or.jp/gaimuin/' },
  { name: '中小企業診断士', alias: 'shindanshi しんだんし 診断士 経営 コンサル', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.j-smeca.jp/' },
  { name: '公認会計士', alias: 'kaikeishi かいけいし 会計士 cpa', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.fsa.go.jp/cpaaob/' },
  { name: '税理士', alias: 'zeirishi ぜいりし 税理士 税務', category: '会計・金融',
    scoreType: 'pass', url: 'https://www.nta.go.jp/taxes/zeirishi/zeirishishiken/', memo: '科目合格制。5科目合格で官報合格。' },
  { name: 'USCPA（米国公認会計士）', alias: 'uscpa 米国公認会計士 会計 英語', category: '会計・金融',
    scoreType: 'score', targetScore: 75, maxScore: 99, scoreUnit: '点',
    url: 'https://nasba.org/' },
  { name: 'ビジネス会計検定2級', alias: 'びじねすかいけい 会計 財務諸表', category: '会計・金融',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.b-accounting.jp/' },

  /* ---------- 法律 ---------- */
  { name: '行政書士', alias: 'gyosei ぎょうせいしょし 行書 法律', category: '法律',
    scoreType: 'score', targetScore: 180, maxScore: 300, scoreUnit: '点',
    url: 'https://gyosei-shiken.or.jp/', memo: '法令等・一般知識それぞれに足切りあり。' },
  { name: '司法書士', alias: 'shoshi しほうしょし 法律 登記', category: '法律',
    scoreType: 'pass', url: 'https://www.moj.go.jp/shikaku_saiyo_index2.html' },
  { name: '社会保険労務士', alias: 'sharoshi しゃろうし 社労士 労務 年金', category: '法律',
    scoreType: 'pass', url: 'https://www.sharosi-siken.or.jp/' },
  { name: '弁理士', alias: 'べんりし 特許 知財', category: '法律',
    scoreType: 'pass', url: 'https://www.jpo.go.jp/news/benrishi/' },
  { name: '司法試験予備試験', alias: 'よびしけん 司法試験 法律', category: '法律',
    scoreType: 'pass', url: 'https://www.moj.go.jp/jinji/shihoushiken/' },
  { name: 'ビジネス実務法務検定2級', alias: 'ほうむけんてい ビジ法 法律', category: '法律',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.kentei.org/houmu/' },
  { name: 'ビジネス実務法務検定3級', alias: 'ほうむけんてい ビジ法 法律', category: '法律',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.kentei.org/houmu/' },
  { name: '知的財産管理技能検定2級', alias: 'ちざい 知財 特許 商標', category: '法律',
    scoreType: 'pass', url: 'https://www.kentei-info-ip-edu.org/', memo: '学科・実技それぞれ80%以上で合格。' },
  { name: '個人情報保護士', alias: 'こじんじょうほう プライバシー セキュリティ', category: '法律',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '%',
    url: 'https://www.joho-gakushu.or.jp/piip/' },

  /* ---------- 不動産・建築 ---------- */
  { name: '宅地建物取引士', alias: 'takken たっけん 宅建 宅建士 不動産', category: '不動産・建築',
    scoreType: 'score', targetScore: 38, maxScore: 50, scoreUnit: '点', fee: 8200,
    url: 'https://www.retio.or.jp/exam/', memo: '合格ラインは相対評価で毎年変動（おおむね35点前後）。' },
  { name: '賃貸不動産経営管理士', alias: 'ちんかん 賃管 不動産 賃貸', category: '不動産・建築',
    scoreType: 'score', targetScore: 36, maxScore: 50, scoreUnit: '点',
    url: 'https://www.chintaikanrishi.jp/' },
  { name: 'マンション管理士', alias: 'マン管 まんかん 不動産 管理', category: '不動産・建築',
    scoreType: 'score', targetScore: 38, maxScore: 50, scoreUnit: '点',
    url: 'https://www.mankan.org/' },
  { name: '管理業務主任者', alias: 'かんぎょう 管業 不動産 管理', category: '不動産・建築',
    scoreType: 'score', targetScore: 36, maxScore: 50, scoreUnit: '点',
    url: 'https://www.kanrikyo.or.jp/' },
  { name: '二級建築士', alias: 'けんちくし 建築 二級', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.jaeic.or.jp/' },
  { name: '一級建築士', alias: 'けんちくし 建築 一級', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.jaeic.or.jp/' },
  { name: '土地家屋調査士', alias: 'ちょうさし 調査士 測量 不動産', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.moj.go.jp/shikaku_saiyo_index3.html' },
  { name: 'インテリアコーディネーター', alias: 'インテリア コーディネーター 住宅', category: '不動産・建築',
    scoreType: 'pass', url: 'https://www.interior.or.jp/' },

  /* ---------- 技術・工業 ---------- */
  { name: '危険物取扱者 乙種第4類', alias: 'kikenbutsu きけんぶつ 乙4 おつよん 危険物', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.shoubo-shiken.or.jp/', memo: '3科目それぞれ60%以上で合格。' },
  { name: '第二種電気工事士', alias: 'denko でんこう 電工二種 電気 工事', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.shiken.or.jp/', memo: '学科試験合格後に技能試験あり。' },
  { name: '第一種電気工事士', alias: 'denko でんこう 電工一種 電気 工事', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.shiken.or.jp/' },
  { name: '第三種電気主任技術者（電験三種）', alias: 'denken でんけん 電験三種 電気 主任技術者', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.shiken.or.jp/', memo: '4科目それぞれ60点以上。科目合格制。' },
  { name: '消防設備士 乙種第6類', alias: 'しょうぼう 乙6 消火器 消防', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.shoubo-shiken.or.jp/' },
  { name: 'エネルギー管理士', alias: 'エネ管 えねかん 省エネ', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.eccj.or.jp/' },
  { name: '第一種衛生管理者', alias: 'えいせいかんりしゃ 衛生 労働安全', category: '技術・工業',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.exam.or.jp/', memo: '総得点60%以上かつ各科目40%以上。' },
  { name: 'QC検定2級', alias: 'qc 品質管理 ひんしつ', category: '技術・工業',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '%',
    url: 'https://webdesk.jsa.or.jp/common/W10K0500/index/qc/' },
  { name: '技術士第一次試験', alias: 'ぎじゅつし 技術士 jabee', category: '技術・工業',
    scoreType: 'score', targetScore: 50, maxScore: 100, scoreUnit: '%',
    url: 'https://www.engineer.or.jp/' },
  { name: '実用数学技能検定（数検）準1級', alias: 'suken すうけん 数検 数学', category: '技術・工業',
    scoreType: 'pass', url: 'https://www.su-gaku.net/' },

  /* ---------- 医療・福祉 ---------- */
  { name: '登録販売者', alias: 'とうろくはんばいしゃ 医薬品 ドラッグストア', category: '医療・福祉',
    scoreType: 'score', targetScore: 84, maxScore: 120, scoreUnit: '点',
    url: 'https://www.mhlw.go.jp/', memo: '総得点70%以上かつ各章35〜40%以上（都道府県により異なる）。' },
  { name: '介護福祉士', alias: 'kaigo かいごふくしし 介護 福祉', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.sssc.or.jp/kaigo/' },
  { name: '社会福祉士', alias: 'しゃかいふくしし 福祉 ソーシャルワーカー', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.sssc.or.jp/shakai/' },
  { name: '精神保健福祉士', alias: 'せいしんほけんふくしし 福祉 メンタル', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.sssc.or.jp/seishin/' },
  { name: '保育士', alias: 'hoikushi ほいくし 保育 こども', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.hoyokyo.or.jp/exam/', memo: '筆記は各科目6割以上。科目合格は3年有効。' },
  { name: '看護師国家試験', alias: 'kangoshi かんごし 看護 医療', category: '医療・福祉',
    scoreType: 'pass', url: 'https://www.mhlw.go.jp/kouseiroudoushou/shikaku_shiken/kangoshi/' },
  { name: '公認心理師', alias: 'こうにんしんりし 心理 カウンセラー', category: '医療・福祉',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000116049.html' },

  /* ---------- ビジネス・一般 ---------- */
  { name: '秘書検定2級', alias: 'hisho ひしょけんてい 秘書 ビジネスマナー', category: 'ビジネス',
    scoreType: 'pass', url: 'https://jitsumu-kentei.jp/HS/index', memo: '理論・実技それぞれ60%以上で合格。' },
  { name: '秘書検定準1級', alias: 'hisho ひしょけんてい 秘書 ビジネスマナー', category: 'ビジネス',
    scoreType: 'pass', url: 'https://jitsumu-kentei.jp/HS/index' },
  { name: 'リテールマーケティング（販売士）2級', alias: 'はんばいし 販売士 リテール 小売', category: 'ビジネス',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点',
    url: 'https://www.kentei.ne.jp/retailsales' },
  { name: '国内旅行業務取扱管理者', alias: 'りょこうぎょうむ 旅行 国内 ツアー', category: 'ビジネス',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.anta.or.jp/' },
  { name: '総合旅行業務取扱管理者', alias: 'りょこうぎょうむ 旅行 総合 海外 ツアー', category: 'ビジネス',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.jata-net.or.jp/' },
  { name: '通関士', alias: 'つうかんし 通関 貿易', category: 'ビジネス',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '%',
    url: 'https://www.customs.go.jp/tsukanshi/' },
  { name: '日本漢字能力検定 2級', alias: 'kanken かんけん 漢検 漢字', category: '語学',
    scoreType: 'score', targetScore: 160, maxScore: 200, scoreUnit: '点',
    url: 'https://www.kanken.or.jp/kanken/', memo: '80%程度で合格。' },
  { name: '普通自動車第一種運転免許', alias: 'menkyo うんてんめんきょ 車 免許 普通免許', category: '車・運転',
    scoreType: 'pass', memo: '学科90点以上／100点満点。' },
  { name: '普通自動二輪免許', alias: 'ばいく バイク 二輪 免許', category: '車・運転',
    scoreType: 'pass' },
  { name: '大型自動二輪免許', alias: 'ばいく バイク 大型二輪 免許', category: '車・運転',
    scoreType: 'pass' },
  { name: '国家公務員一般職試験（大卒程度）', alias: 'こうむいん 公務員 国家一般職', category: '公務員・教育',
    scoreType: 'pass', url: 'https://www.jinji.go.jp/saiyo/saiyo.html' },
  { name: '地方公務員上級（都道府県・政令市）', alias: 'こうむいん 公務員 地方上級', category: '公務員・教育',
    scoreType: 'pass' },
  { name: '教員採用試験', alias: 'きょういん 教員 教採 先生', category: '公務員・教育',
    scoreType: 'pass' },

  /* ==================================================================
     ここから下は、名前・カテゴリを中心に収録した幅広い検定。
     合格基準が公表されていないものは scoreType を省略している。
     その場合は評価方式「スコア」のまま、目標は自分で決める。
     ================================================================== */

  /* ---------- 歴史・地理 ---------- */
  { name: '世界遺産検定 4級', alias: 'せかいいさん 世界遺産 せかけん 教養', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 3800,
    url: 'https://www.sekaken.jp/', memo: '100点満点中60点以上で認定。' },
  { name: '世界遺産検定 3級', alias: 'せかいいさん 世界遺産 せかけん 教養', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 5400,
    url: 'https://www.sekaken.jp/', memo: '100点満点中60点以上で認定。' },
  { name: '世界遺産検定 2級', alias: 'せかいいさん 世界遺産 せかけん 教養', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 6500,
    url: 'https://www.sekaken.jp/', memo: '100点満点中60点以上で認定。' },
  { name: '世界遺産検定 準1級', alias: 'せかいいさん 世界遺産 せかけん 教養', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 7600,
    url: 'https://www.sekaken.jp/', memo: '100点満点中60点以上で認定。' },
  { name: '世界遺産検定 1級', alias: 'せかいいさん 世界遺産 せかけん 教養', category: '歴史・地理',
    scoreType: 'score', targetScore: 140, maxScore: 200, scoreUnit: '点', fee: 10900,
    url: 'https://www.sekaken.jp/', memo: '200点満点中140点以上で認定。' },
  { name: '世界遺産検定 マイスター', alias: 'せかいいさん 世界遺産 せかけん 教養', category: '歴史・地理',
    scoreType: 'pass', fee: 20400, url: 'https://www.sekaken.jp/', memo: '認定基準は非公開。1級認定者が対象。' },

  { name: '歴史能力検定 5級（歴史入門）', alias: 'れきけん 歴検 歴史 れきし', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 4級（歴史基本）', alias: 'れきけん 歴検 歴史 れきし', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 準3級（日本史）', alias: 'れきけん 歴検 歴史 日本史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 3級（日本史）', alias: 'れきけん 歴検 歴史 日本史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 3級（世界史）', alias: 'れきけん 歴検 歴史 世界史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 2級（日本史）', alias: 'れきけん 歴検 歴史 日本史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 2級（世界史）', alias: 'れきけん 歴検 歴史 世界史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 1級（日本史）', alias: 'れきけん 歴検 歴史 日本史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },
  { name: '歴史能力検定 1級（世界史）', alias: 'れきけん 歴検 歴史 世界史', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.rekiken.gr.jp/', memo: '各級100点満点、正答率60%が合格の目安。' },

  { name: '地図地理検定 基礎', alias: 'ちずちり 地図 地理 ちずけん', category: '歴史・地理',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点',
    url: 'https://www.jmc.or.jp/keihatsu-kyouiku/chizuken/', memo: '基礎は100点満点中60点以上が合格基準。' },
  { name: '地図地理検定 専門', alias: 'ちずちり 地図 地理 ちずけん', category: '歴史・地理',
    url: 'https://www.jmc.or.jp/keihatsu-kyouiku/chizuken/' },

  { name: '日本城郭検定', alias: 'じょうかく 城 しろ お城 城郭', category: '歴史・地理' },
  { name: '考古検定', alias: 'こうこ 考古学 遺跡', category: '歴史・地理' },
  { name: '考古調査士', alias: 'こうこちょうさし 考古学 発掘', category: '歴史・地理' },
  { name: '戦史検定', alias: 'せんし 戦史 戦争 近現代史', category: '歴史・地理' },
  { name: '旅行地理検定', alias: 'りょこうちり 旅行 地理 旅', category: '歴史・地理' },
  { name: '日本伝統文化検定（伝検）', alias: 'でんけん 伝統文化 日本文化', category: '歴史・地理' },
  { name: '神社検定（神道文化検定）', alias: 'じんじゃ 神社 神道 しんとう', category: '歴史・地理' },
  { name: '社会科能力検定', alias: 'しゃかいか 社会科 社会', category: '歴史・地理' },
  { name: '地域調査士', alias: 'ちいきちょうさし 地理 地域', category: '歴史・地理' },
  { name: 'GIS学術士', alias: 'gis 地理情報 地理', category: '歴史・地理' },
  { name: '学芸員', alias: 'がくげいいん 博物館 美術館', category: '歴史・地理', scoreType: 'pass' },
  { name: '測量士', alias: 'そくりょうし 測量 そくりょう', category: '歴史・地理', scoreType: 'pass' },
  { name: '測量士補', alias: 'そくりょうしほ 測量 そくりょう', category: '歴史・地理', scoreType: 'pass' },
  { name: '中国百科検定', alias: 'ちゅうごくひゃっか 中国 百科', category: '歴史・地理' },

  /* ---------- 理科・数学 ---------- */
  { name: '天文宇宙検定 4級（星博士ジュニア）', alias: 'てんもん 天文 宇宙 星 astro', category: '理科・数学',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 4400,
    url: 'https://www.astro-test.org/', memo: '40問・100点満点、60点以上で合格。' },
  { name: '天文宇宙検定 3級（星空博士）', alias: 'てんもん 天文 宇宙 星 astro', category: '理科・数学',
    scoreType: 'score', targetScore: 60, maxScore: 100, scoreUnit: '点', fee: 5000,
    url: 'https://www.astro-test.org/', memo: '60問・100点満点、60点以上で合格。' },
  { name: '天文宇宙検定 2級（銀河博士）', alias: 'てんもん 天文 宇宙 星 astro', category: '理科・数学',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 6200,
    url: 'https://www.astro-test.org/', memo: '60問・100点満点、70点以上で合格。' },
  { name: '天文宇宙検定 1級（天文宇宙博士）', alias: 'てんもん 天文 宇宙 星 astro', category: '理科・数学',
    scoreType: 'score', targetScore: 70, maxScore: 100, scoreUnit: '点', fee: 6700,
    url: 'https://www.astro-test.org/', memo: '40問・100点満点、70点以上で合格。2級合格者が対象。' },

  { name: '実用数学技能検定（数検）2級', alias: 'suken すうけん 数検 数学', category: '理科・数学',
    scoreType: 'pass', url: 'https://www.su-gaku.net/' },
  { name: '実用数学技能検定（数検）3級', alias: 'suken すうけん 数検 数学', category: '理科・数学',
    scoreType: 'pass', url: 'https://www.su-gaku.net/' },
  { name: '算数・数学思考力検定', alias: 'しこうりょく 算数 数学 思考力', category: '理科・数学' },
  { name: '日本理科学検定（理検）', alias: 'りけん 理科 理検 science', category: '理科・数学' },
  { name: '実用理科技能検定', alias: 'りかけんてい 理科 science', category: '理科・数学' },
  { name: '生物分類技能検定', alias: 'せいぶつぶんるい 生物 自然 いきもの', category: '理科・数学' },
  { name: 'バイオ技術者認定試験', alias: 'ばいお バイオ 生物 技術者', category: '理科・数学' },
  { name: '気象予報士', alias: 'kisho きしょうよほうし 天気 気象', category: '理科・数学',
    scoreType: 'pass', url: 'https://www.jmbsc.or.jp/jp/examination/examination.html' },
  { name: '天気検定', alias: 'てんき 天気 気象', category: '理科・数学' },
  { name: '統計検定 3級', alias: 'toukei とうけい 統計 データ分析', category: '理科・数学',
    url: 'https://www.toukei-kentei.jp/' },
  { name: '統計検定 準1級', alias: 'toukei とうけい 統計 データ分析', category: '理科・数学',
    url: 'https://www.toukei-kentei.jp/' },
  { name: '統計検定 1級', alias: 'toukei とうけい 統計 データ分析', category: '理科・数学',
    url: 'https://www.toukei-kentei.jp/' },
  { name: '統計検定 データサイエンス基礎', alias: 'toukei 統計 データサイエンス ds', category: '理科・数学',
    url: 'https://www.toukei-kentei.jp/' },
  { name: '計算技術検定', alias: 'けいさんぎじゅつ 計算 工業', category: '理科・数学' },
  { name: '計算力・思考力検定', alias: 'けいさんりょく 計算 思考力', category: '理科・数学' },
  { name: '珠算能力検定（日商珠算）', alias: 'しゅざん そろばん 珠算 abacus', category: '理科・数学' },
  { name: '暗算検定', alias: 'あんざん 暗算 そろばん', category: '理科・数学' },
  { name: '電卓計算能力検定', alias: 'でんたく 電卓 計算', category: '理科・数学' },

  /* ---------- 趣味・カルチャー ---------- */
  { name: 'ねこ検定', alias: 'ねこ 猫 キャット ペット', category: '趣味・カルチャー' },
  { name: '日本さかな検定（ととけん）', alias: 'ととけん さかな 魚 うお', category: '趣味・カルチャー' },
  { name: '夜景鑑賞士検定', alias: 'やけい 夜景 鑑賞', category: '趣味・カルチャー' },
  { name: 'サウナ検定（サ検）', alias: 'さうな サウナ ととのう', category: '趣味・カルチャー' },
  { name: 'くるまマイスター検定', alias: 'くるま 車 自動車 マイスター', category: '趣味・カルチャー' },
  { name: '時刻表検定', alias: 'じこくひょう 時刻表 鉄道 電車', category: '趣味・カルチャー' },
  { name: '鉄道検定', alias: 'てつどう 鉄道 電車 てつ', category: '趣味・カルチャー' },
  { name: '映画検定', alias: 'えいが 映画 シネマ', category: '趣味・カルチャー' },
  { name: '全国総合アニメ文化知識検定試験', alias: 'あにめ アニメ 漫画 オタク', category: '趣味・カルチャー' },
  { name: '漫画能力検定', alias: 'まんが 漫画 マンガ イラスト', category: '趣味・カルチャー' },
  { name: '似顔絵検定', alias: 'にがおえ 似顔絵 イラスト', category: '趣味・カルチャー' },
  { name: '宝塚歌劇検定', alias: 'たからづか 宝塚 歌劇 タカラヅカ', category: '趣味・カルチャー' },
  { name: '松竹歌舞伎検定', alias: 'かぶき 歌舞伎 松竹 伝統芸能', category: '趣味・カルチャー' },
  { name: 'サッカー検定', alias: 'さっかー サッカー football', category: '趣味・カルチャー' },
  { name: '天然石検定', alias: 'てんねんせき 天然石 パワーストーン 鉱物', category: '趣味・カルチャー' },
  { name: 'タロット検定', alias: 'たろっと タロット 占い', category: '趣味・カルチャー' },
  { name: 'サンタクロース検定', alias: 'さんた サンタ クリスマス', category: '趣味・カルチャー' },
  { name: 'けん玉検定', alias: 'けんだま けん玉 kendama', category: '趣味・カルチャー' },
  { name: 'クレーンゲーム達人検定', alias: 'くれーんげーむ クレーンゲーム ufoキャッチャー', category: '趣味・カルチャー' },
  { name: 'ホームパーティー検定', alias: 'ほーむぱーてぃー パーティー おもてなし', category: '趣味・カルチャー' },
  { name: '花検定', alias: 'はなけんてい 花 フラワー', category: '趣味・カルチャー' },
  { name: '茶道文化検定', alias: 'さどう 茶道 お茶 抹茶', category: '趣味・カルチャー' },
  { name: 'きもの文化検定', alias: 'きもの 着物 和装', category: '趣味・カルチャー' },
  { name: '声優能力検定', alias: 'せいゆう 声優 アニメ', category: '趣味・カルチャー' },
  { name: 'ニュース時事能力検定（N検）', alias: 'nけん じじ 時事 ニュース', category: '趣味・カルチャー' },
  { name: 'ドローン検定（無人航空従事者試験）', alias: 'どろーん ドローン drone 無人航空', category: '趣味・カルチャー' },
  { name: 'モールス電信技能認定', alias: 'もーるす モールス 無線 アマチュア無線', category: '趣味・カルチャー' },
  { name: '第四級アマチュア無線技士', alias: 'あまちゅあむせん アマチュア無線 4アマ ham', category: '趣味・カルチャー' },
  { name: '第三級アマチュア無線技士', alias: 'あまちゅあむせん アマチュア無線 3アマ ham', category: '趣味・カルチャー' },
  { name: '終活カウンセラー検定', alias: 'しゅうかつ 終活 相続', category: '趣味・カルチャー' },
  { name: '消費生活能力検定', alias: 'しょうひせいかつ 消費生活 くらし', category: '趣味・カルチャー' },
  { name: '住育検定', alias: 'じゅういく 住まい 住宅', category: '趣味・カルチャー' },
  { name: '洗車検定', alias: 'せんしゃ 洗車 車', category: '趣味・カルチャー' },
  { name: 'イベント検定（イベント業務管理者）', alias: 'いべんと イベント 運営', category: '趣味・カルチャー' },
  { name: '観光特産士検定', alias: 'かんこうとくさん 観光 特産 おみやげ', category: '趣味・カルチャー' },


  /* ---------- ご当地検定 ---------- */
  { name: '京都・観光文化検定（京都検定）', alias: 'きょうと 京都 きょうとけんてい ごとうち', category: 'ご当地' },
  { name: '東京シティガイド検定', alias: 'とうきょう 東京 ガイド ごとうち', category: 'ご当地' },
  { name: '大阪検定（なにわなんでも大阪検定）', alias: 'おおさか 大阪 なにわ ごとうち', category: 'ご当地' },
  { name: '北海道観光マスター検定', alias: 'ほっかいどう 北海道 観光 ごとうち', category: 'ご当地' },
  { name: '道産子検定', alias: 'どさんこ 北海道 ごとうち', category: 'ご当地' },
  { name: '博多・言うたらなんやけど検定', alias: 'はかた 博多 福岡 ごとうち', category: 'ご当地' },
  { name: '会津ものしり検定', alias: 'あいづ 会津 福島 ごとうち', category: 'ご当地' },
  { name: 'いわき学検定', alias: 'いわき 福島 ごとうち', category: 'ご当地' },
  { name: 'いまばり博士検定', alias: 'いまばり 今治 愛媛 ごとうち', category: 'ご当地' },
  { name: '沖縄大好き検定', alias: 'おきなわ 沖縄 ごとうち', category: 'ご当地' },
  { name: '境港妖怪検定', alias: 'さかいみなと 境港 妖怪 鳥取 ごとうち', category: 'ご当地' },
  { name: '四国観光検定', alias: 'しこく 四国 観光 ごとうち', category: 'ご当地' },
  { name: '萩ものしり博士検定', alias: 'はぎ 萩 山口 ごとうち', category: 'ご当地' },
  { name: '函館歴史文化観光検定', alias: 'はこだて 函館 北海道 ごとうち', category: 'ご当地' },
  { name: '晴れの国おかやま検定', alias: 'おかやま 岡山 ごとうち', category: 'ご当地' },
  { name: '奈良まほろばソムリエ検定', alias: 'なら 奈良 まほろば ごとうち', category: 'ご当地' },
  { name: '神戸学検定', alias: 'こうべ 神戸 兵庫 ごとうち', category: 'ご当地' },
  { name: '金沢検定', alias: 'かなざわ 金沢 石川 ごとうち', category: 'ご当地' },
  { name: '名古屋観光検定', alias: 'なごや 名古屋 愛知 ごとうち', category: 'ご当地' },
  { name: '広島検定', alias: 'ひろしま 広島 ごとうち', category: 'ご当地' },
  { name: '仙台・宮城観光検定', alias: 'せんだい 仙台 宮城 ごとうち', category: 'ご当地' },
  { name: '横浜シティガイド検定', alias: 'よこはま 横浜 神奈川 ごとうち', category: 'ご当地' },
  { name: '鎌倉観光文化検定', alias: 'かまくら 鎌倉 神奈川 ごとうち', category: 'ご当地' },
  { name: '長崎歴史文化観光検定', alias: 'ながさき 長崎 ごとうち', category: 'ご当地' },
  { name: '信州・長野県観光文化検定', alias: 'ながの 長野 信州 ごとうち', category: 'ご当地' },

  /* ---------- 食・料理 ---------- */
  { name: '食生活アドバイザー', alias: 'しょくせいかつ 食生活 食 栄養', category: '食・料理' },
  { name: 'フードコーディネーター', alias: 'ふーどこーでぃねーたー フード 料理', category: '食・料理' },
  { name: 'フードアナリスト検定', alias: 'ふーどあなりすと フード 食 グルメ', category: '食・料理' },
  { name: '家庭料理技能検定（料検）', alias: 'りょうけん 料理 家庭料理 クッキング', category: '食・料理' },
  { name: '料理検定', alias: 'りょうり 料理 クッキング', category: '食・料理' },
  { name: '菓子検定', alias: 'かし 菓子 お菓子 スイーツ', category: '食・料理' },
  { name: 'スイーツ検定', alias: 'すいーつ スイーツ お菓子 デザート', category: '食・料理' },
  { name: 'チョコレート検定', alias: 'ちょこれーと チョコレート カカオ', category: '食・料理' },
  { name: 'パンシェルジュ検定', alias: 'ぱん パン ベーカリー', category: '食・料理' },
  { name: 'コーヒーインストラクター検定', alias: 'こーひー コーヒー 珈琲 カフェ', category: '食・料理' },
  { name: 'J.S.A. ソムリエ', alias: 'そむりえ ソムリエ ワイン wine', category: '食・料理' },
  { name: 'J.S.A. ワインエキスパート', alias: 'わいん ワイン エキスパート wine', category: '食・料理' },
  { name: '日本酒検定', alias: 'にほんしゅ 日本酒 酒 sake', category: '食・料理' },
  { name: '唎酒師（ききさけし）', alias: 'ききさけし 日本酒 酒 sake', category: '食・料理' },
  { name: '焼酎検定', alias: 'しょうちゅう 焼酎 酒', category: '食・料理' },
  { name: 'ビール検定（びあけん）', alias: 'びあけん ビール beer 酒', category: '食・料理' },
  { name: '野菜ソムリエ', alias: 'やさい 野菜 ソムリエ ベジタブル', category: '食・料理' },
  { name: '食品表示検定', alias: 'しょくひんひょうじ 食品表示 食品', category: '食・料理' },
  { name: '食品安全検定', alias: 'しょくひんあんぜん 食品安全 衛生', category: '食・料理' },
  { name: '栄養検定', alias: 'えいよう 栄養 食', category: '食・料理' },
  { name: '日本食文化検定（和食検定）', alias: 'わしょく 和食 日本食 食文化', category: '食・料理' },
  { name: 'すしエキスパート検定', alias: 'すし 寿司 鮨', category: '食・料理' },
  { name: '調理師', alias: 'ちょうりし 調理師 料理 コック', category: '食・料理', scoreType: 'pass' },
  { name: '製菓衛生師', alias: 'せいかえいせいし 製菓 パティシエ お菓子', category: '食・料理', scoreType: 'pass' },
  { name: '管理栄養士', alias: 'かんりえいようし 栄養士 栄養', category: '食・料理', scoreType: 'pass' },
  { name: '栄養士', alias: 'えいようし 栄養 食事', category: '食・料理', scoreType: 'pass' },
  { name: '食品衛生責任者', alias: 'しょくひんえいせい 食品衛生 飲食', category: '食・料理', scoreType: 'pass' },
  { name: '惣菜管理士', alias: 'そうざい 惣菜 食品', category: '食・料理' },

  /* ---------- デザイン・美術 ---------- */
  { name: '色彩検定 3級', alias: 'しきさい 色彩 カラー color', category: 'デザイン・美術' },
  { name: '色彩検定 2級', alias: 'しきさい 色彩 カラー color', category: 'デザイン・美術' },
  { name: '色彩検定 1級', alias: 'しきさい 色彩 カラー color', category: 'デザイン・美術' },
  { name: '色彩検定 UC級', alias: 'しきさい 色彩 カラー ユニバーサルデザイン', category: 'デザイン・美術' },
  { name: 'カラーコーディネーター検定試験', alias: 'からーこーでぃねーたー カラー 色彩', category: 'デザイン・美術' },
  { name: '色彩士検定', alias: 'しきさいし 色彩 カラー', category: 'デザイン・美術' },
  { name: '美術検定', alias: 'びじゅつ 美術 アート art', category: 'デザイン・美術' },
  { name: 'フォトマスター検定', alias: 'ふぉと 写真 カメラ photo', category: 'デザイン・美術' },
  { name: 'Webデザイナー検定', alias: 'うぇぶでざいなー web デザイン', category: 'デザイン・美術' },
  { name: 'CGクリエイター検定', alias: 'cg クリエイター 3d', category: 'デザイン・美術' },
  { name: 'CGエンジニア検定', alias: 'cg エンジニア 3d', category: 'デザイン・美術' },
  { name: '画像処理エンジニア検定', alias: 'がぞうしょり 画像処理 image', category: 'デザイン・美術' },
  { name: 'マルチメディア検定', alias: 'まるちめでぃあ マルチメディア', category: 'デザイン・美術' },
  { name: 'Illustratorクリエイター能力認定試験', alias: 'illustrator イラレ デザイン adobe', category: 'デザイン・美術' },
  { name: 'Photoshopクリエイター能力認定試験', alias: 'photoshop フォトショ デザイン adobe', category: 'デザイン・美術' },
  { name: 'Webクリエイター能力認定試験', alias: 'web クリエイター html css', category: 'デザイン・美術' },
  { name: 'レタリング技能検定', alias: 'れたりんぐ レタリング 文字 デザイン', category: 'デザイン・美術' },
  { name: 'トレース技能検定', alias: 'とれーす トレース 製図', category: 'デザイン・美術' },
  { name: 'POP広告クリエイター技能審査試験', alias: 'pop 広告 ポップ', category: 'デザイン・美術' },
  { name: '毛筆書写技能検定', alias: 'もうひつ 書写 書道 しょどう', category: 'デザイン・美術' },
  { name: '硬筆書写技能検定', alias: 'こうひつ 書写 ペン字 書道', category: 'デザイン・美術' },
  { name: 'インテリアコーディネーター（IC）', alias: 'いんてりあ インテリア 住宅', category: 'デザイン・美術' },
  { name: 'インテリアプランナー', alias: 'いんてりあ インテリア 設計', category: 'デザイン・美術' },
  { name: '照明コンサルタント', alias: 'しょうめい 照明 ライティング', category: 'デザイン・美術' },

  /* ---------- 音楽・芸能 ---------- */
  { name: 'ヤマハ音楽能力検定（ヤマハグレード）', alias: 'やまは ヤマハ 音楽 ピアノ', category: '音楽・芸能' },
  { name: '音楽検定', alias: 'おんがく 音楽 ミュージック', category: '音楽・芸能' },
  { name: '楽譜検定', alias: 'がくふ 楽譜 音楽', category: '音楽・芸能' },
  { name: 'MIDI検定', alias: 'midi ミディ 音楽 dtm', category: '音楽・芸能' },
  { name: '音響技術者能力検定', alias: 'おんきょう 音響 pa サウンド', category: '音楽・芸能' },
  { name: 'ラジオ音響技能検定', alias: 'らじお ラジオ 音響', category: '音楽・芸能' },
  { name: 'ストリートダンス検定', alias: 'だんす ダンス ストリート', category: '音楽・芸能' },
  { name: 'ピアノ演奏グレード', alias: 'ぴあの ピアノ 演奏', category: '音楽・芸能' },

  /* ---------- 服飾・美容 ---------- */
  { name: 'JNECネイリスト技能検定試験', alias: 'ねいる ネイル nail', category: '服飾・美容' },
  { name: 'JNAジェルネイル技能検定試験', alias: 'じぇるねいる ジェルネイル ネイル', category: '服飾・美容' },
  { name: '日本化粧品検定（コスメ検定）', alias: 'こすめ コスメ 化粧品 美容', category: '服飾・美容' },
  { name: '化粧品成分検定', alias: 'せいぶん 化粧品 成分 コスメ', category: '服飾・美容' },
  { name: 'メイクセラピー検定', alias: 'めいく メイク 化粧 美容', category: '服飾・美容' },
  { name: '美容師', alias: 'びようし 美容師 美容 ヘア', category: '服飾・美容', scoreType: 'pass' },
  { name: '理容師', alias: 'りようし 理容師 床屋 ヘア', category: '服飾・美容', scoreType: 'pass' },
  { name: 'アロマテラピー検定', alias: 'あろま アロマ 香り', category: '服飾・美容' },
  { name: '環境カオリスタ検定', alias: 'かおりすた アロマ 香り 環境', category: '服飾・美容' },
  { name: 'ハーブ検定', alias: 'はーぶ ハーブ 薬草', category: '服飾・美容' },
  { name: 'ファッションビジネス能力検定', alias: 'ふぁっしょん ファッション アパレル', category: '服飾・美容' },
  { name: 'ファッション販売能力検定', alias: 'ふぁっしょん ファッション 販売 アパレル', category: '服飾・美容' },
  { name: 'ファッション色彩能力検定', alias: 'ふぁっしょん ファッション 色彩 カラー', category: '服飾・美容' },
  { name: 'パターンメーキング技術検定', alias: 'ぱたーん パターン 洋裁 縫製', category: '服飾・美容' },
  { name: '洋裁技術検定', alias: 'ようさい 洋裁 縫製 ソーイング', category: '服飾・美容' },
  { name: '和裁検定試験', alias: 'わさい 和裁 着物 縫製', category: '服飾・美容' },
  { name: '毛糸編物技能検定', alias: 'あみもの 編物 ニット 毛糸', category: '服飾・美容' },
  { name: 'レース編物技能検定', alias: 'れーす レース 編物 ニット', category: '服飾・美容' },
  { name: 'ジュエリーコーディネーター検定', alias: 'じゅえりー ジュエリー 宝石 アクセサリー', category: '服飾・美容' },
  { name: '宝石鑑定士（FGA・DGA）', alias: 'ほうせき 宝石 ジェモロジー fga', category: '服飾・美容' },
  { name: 'タオルソムリエ', alias: 'たおる タオル 今治', category: '服飾・美容' },


  /* ---------- 動物・自然・環境 ---------- */
  { name: '獣医師', alias: 'じゅういし 獣医 動物', category: '動物・自然', scoreType: 'pass' },
  { name: '愛玩動物看護師', alias: 'あいがんどうぶつ 動物看護 ペット', category: '動物・自然', scoreType: 'pass' },
  { name: '愛玩動物飼養管理士', alias: 'しようかんりし ペット 動物 愛玩', category: '動物・自然' },
  { name: 'ドッグトレーナー', alias: 'どっぐとれーなー 犬 いぬ しつけ', category: '動物・自然' },
  { name: 'トリマー（JKC公認）', alias: 'とりまー トリマー 犬 ペット', category: '動物・自然' },
  { name: 'ペット栄養管理士', alias: 'ぺっと ペット 栄養 動物', category: '動物・自然' },
  { name: '狩猟免許（第一種銃猟）', alias: 'しゅりょう 狩猟 猟 ハンター', category: '動物・自然', scoreType: 'pass' },
  { name: '狩猟免許（わな猟）', alias: 'しゅりょう 狩猟 わな 猟', category: '動物・自然', scoreType: 'pass' },
  { name: '環境社会検定試験（eco検定）', alias: 'eco えこ エコ 環境 環境社会', category: '動物・自然' },
  { name: '3R・低炭素社会検定', alias: '3r リサイクル 環境 低炭素', category: '動物・自然' },
  { name: 'リユース検定', alias: 'りゆーす リユース リサイクル 環境', category: '動物・自然' },
  { name: '公害防止管理者', alias: 'こうがい 公害 環境 大気 水質', category: '動物・自然', scoreType: 'pass' },
  { name: 'グリーンセイバー検定', alias: 'ぐりーんせいばー 植物 樹木 自然', category: '動物・自然' },
  { name: '樹木医', alias: 'じゅもくい 樹木 木 植物', category: '動物・自然' },
  { name: '森林インストラクター', alias: 'しんりん 森林 森 自然', category: '動物・自然' },
  { name: '自然観察指導員', alias: 'しぜんかんさつ 自然 観察', category: '動物・自然' },
  { name: 'ビオトープ管理士', alias: 'びおとーぷ ビオトープ 環境 自然', category: '動物・自然' },
  { name: '造園技能士', alias: 'ぞうえん 造園 庭 ガーデニング', category: '動物・自然' },
  { name: '園芸装飾技能士', alias: 'えんげい 園芸 植物 グリーン', category: '動物・自然' },
  { name: 'フラワーデザイナー（NFD）', alias: 'ふらわー フラワー 花 アレンジメント', category: '動物・自然' },
  { name: '日本農業検定', alias: 'のうぎょう 農業 農 のうけん', category: '動物・自然' },
  { name: '日本農業技術検定', alias: 'のうぎょうぎじゅつ 農業 農', category: '動物・自然' },
  { name: '毒物劇物取扱者', alias: 'どくぶつげきぶつ 毒物 劇物 化学', category: '動物・自然', scoreType: 'pass' },

  /* ---------- スポーツ ---------- */
  { name: '公認スポーツ指導者（コーチングアシスタント）', alias: 'すぽーつ スポーツ 指導者 コーチ', category: 'スポーツ' },
  { name: 'スポーツプログラマー', alias: 'すぽーつ スポーツ プログラマー 指導', category: 'スポーツ' },
  { name: 'ジュニアスポーツ指導員', alias: 'じゅにあ スポーツ 指導 子ども', category: 'スポーツ' },
  { name: 'アスレティックトレーナー', alias: 'とれーなー トレーナー スポーツ at', category: 'スポーツ' },
  { name: '健康運動指導士', alias: 'けんこううんどう 運動 健康 フィットネス', category: 'スポーツ' },
  { name: 'NSCA-CPT（パーソナルトレーナー）', alias: 'nsca ぱーそなる トレーナー 筋トレ', category: 'スポーツ' },
  { name: 'JAFライセンス（国内競技運転者許可証）', alias: 'jaf モータースポーツ レース 車', category: 'スポーツ' },
  { name: 'MFJライセンス', alias: 'mfj バイク モータースポーツ レース', category: 'スポーツ' },
  { name: 'スキー指導員（SAJ）', alias: 'すきー スキー saj ウィンター', category: 'スポーツ' },
  { name: 'スノーボード指導員', alias: 'すのーぼーど スノボ スノーボード', category: 'スポーツ' },
  { name: 'PADIオープンウォーターダイバー', alias: 'padi だいびんぐ ダイビング 潜水 スキューバ', category: 'スポーツ' },
  { name: '潜水士', alias: 'せんすいし 潜水 ダイビング', category: 'スポーツ', scoreType: 'pass' },
  { name: '小型船舶操縦士 2級', alias: 'せんぱく 船舶 ボート 船 免許', category: 'スポーツ', scoreType: 'pass' },
  { name: '小型船舶操縦士 1級', alias: 'せんぱく 船舶 ボート 船 免許', category: 'スポーツ', scoreType: 'pass' },
  { name: 'サッカー公認審判員（4級）', alias: 'さっかー サッカー 審判 レフェリー', category: 'スポーツ' },
  { name: '日本サッカー協会公認C級コーチ', alias: 'さっかー サッカー コーチ jfa', category: 'スポーツ' },
  { name: '囲碁段位認定', alias: 'いご 囲碁 碁', category: 'スポーツ' },
  { name: '将棋段位認定', alias: 'しょうぎ 将棋', category: 'スポーツ' },

  /* ---------- 医療・福祉（追加） ---------- */
  { name: '医療事務技能審査試験（メディカルクラーク）', alias: 'いりょうじむ 医療事務 クラーク', category: '医療・福祉' },
  { name: '診療報酬請求事務能力認定試験', alias: 'しんりょうほうしゅう 医療事務 レセプト', category: '医療・福祉' },
  { name: '医療秘書技能検定', alias: 'いりょうひしょ 医療秘書 医療事務', category: '医療・福祉' },
  { name: '医事コンピュータ技能検定', alias: 'いじこんぴゅーた 医療事務 医事', category: '医療・福祉' },
  { name: '調剤薬局事務', alias: 'ちょうざい 調剤 薬局 事務', category: '医療・福祉' },
  { name: '薬剤師', alias: 'やくざいし 薬剤師 薬', category: '医療・福祉', scoreType: 'pass' },
  { name: '臨床検査技師', alias: 'りんしょうけんさ 臨床検査 検査技師', category: '医療・福祉', scoreType: 'pass' },
  { name: '診療放射線技師', alias: 'ほうしゃせん 放射線技師 レントゲン', category: '医療・福祉', scoreType: 'pass' },
  { name: '理学療法士（PT）', alias: 'りがくりょうほう pt リハビリ', category: '医療・福祉', scoreType: 'pass' },
  { name: '作業療法士（OT）', alias: 'さぎょうりょうほう ot リハビリ', category: '医療・福祉', scoreType: 'pass' },
  { name: '言語聴覚士（ST）', alias: 'げんごちょうかく st リハビリ', category: '医療・福祉', scoreType: 'pass' },
  { name: '救急救命士', alias: 'きゅうきゅうきゅうめい 救急 救命', category: '医療・福祉', scoreType: 'pass' },
  { name: '歯科衛生士', alias: 'しかえいせいし 歯科 歯 衛生士', category: '医療・福祉', scoreType: 'pass' },
  { name: '歯科技工士', alias: 'しかぎこうし 歯科 技工', category: '医療・福祉', scoreType: 'pass' },
  { name: '准看護師', alias: 'じゅんかんごし 看護 准看', category: '医療・福祉', scoreType: 'pass' },
  { name: '介護支援専門員（ケアマネジャー）', alias: 'けあまね ケアマネ 介護支援 介護', category: '医療・福祉', scoreType: 'pass' },
  { name: '介護職員初任者研修', alias: 'しょにんしゃ 介護 ヘルパー 初任者', category: '医療・福祉', scoreType: 'pass' },
  { name: '実務者研修（介護福祉士実務者研修）', alias: 'じつむしゃ 介護 研修', category: '医療・福祉', scoreType: 'pass' },
  { name: '福祉住環境コーディネーター検定', alias: 'ふくしじゅうかんきょう 福祉 住環境 バリアフリー', category: '医療・福祉' },
  { name: 'メンタルヘルス・マネジメント検定', alias: 'めんたるへるす メンタル 心理 ストレス', category: '医療・福祉' },
  { name: '臨床心理士', alias: 'りんしょうしんりし 心理 カウンセラー', category: '医療・福祉' },
  { name: '産業カウンセラー', alias: 'さんぎょうかうんせらー カウンセラー 心理 職場', category: '医療・福祉' },
  { name: '心理学検定', alias: 'しんりがく 心理学 心理', category: '医療・福祉' },
  { name: 'サービス介助士', alias: 'さーびすかいじょし 介助 バリアフリー おもてなし', category: '医療・福祉' },
  { name: '手話技能検定', alias: 'しゅわ 手話 サイン', category: '医療・福祉' },
  { name: '全国手話検定試験', alias: 'しゅわ 手話 サイン', category: '医療・福祉' },
  { name: '点字技能検定', alias: 'てんじ 点字 視覚障害', category: '医療・福祉' },
  { name: '認知症ライフパートナー検定', alias: 'にんちしょう 認知症 介護', category: '医療・福祉' },
  { name: '健康管理能力検定', alias: 'けんこうかんり 健康 生活習慣', category: '医療・福祉' },
  { name: 'ダイエット検定', alias: 'だいえっと ダイエット 健康 体型', category: '医療・福祉' },
  { name: '薬学検定', alias: 'やくがく 薬学 薬', category: '医療・福祉' },
  { name: '柔道整復師', alias: 'じゅうどうせいふくし 整復 接骨 柔整', category: '医療・福祉', scoreType: 'pass' },
  { name: 'はり師・きゅう師', alias: 'はりきゅう 鍼灸 はり きゅう', category: '医療・福祉', scoreType: 'pass' },
  { name: 'あん摩マッサージ指圧師', alias: 'あんま マッサージ 指圧', category: '医療・福祉', scoreType: 'pass' },

  /* ---------- ビジネス（追加） ---------- */
  { name: 'サービス接遇検定', alias: 'せつぐう 接遇 サービス 接客', category: 'ビジネス' },
  { name: 'ビジネス実務マナー技能検定', alias: 'まなー マナー ビジネス 実務', category: 'ビジネス' },
  { name: 'ビジネス文書技能検定', alias: 'ぶんしょ ビジネス文書 文書', category: 'ビジネス' },
  { name: 'ビジネス電話検定', alias: 'でんわ 電話 ビジネス 応対', category: 'ビジネス' },
  { name: 'マナー・プロトコール検定', alias: 'まなー マナー プロトコール 礼儀', category: 'ビジネス' },
  { name: 'ビジネスマネジャー検定試験', alias: 'まねじゃー マネジャー 管理職 ビジネス', category: 'ビジネス' },
  { name: 'ビジネス能力検定（B検）', alias: 'bけん ビジネス能力 ビジネス', category: 'ビジネス' },
  { name: 'ビジネス・キャリア検定', alias: 'きゃりあ キャリア ビジネス', category: 'ビジネス' },
  { name: '経営学検定（マネジメント検定）', alias: 'けいえいがく 経営 マネジメント', category: 'ビジネス' },
  { name: '経済学検定（ERE）', alias: 'けいざいがく 経済 ere', category: 'ビジネス' },
  { name: '商業経済検定', alias: 'しょうぎょうけいざい 商業 経済', category: 'ビジネス' },
  { name: '貿易実務検定', alias: 'ぼうえき 貿易 実務 輸出入', category: 'ビジネス' },
  { name: 'マーケティング・ビジネス実務検定', alias: 'まーけてぃんぐ マーケティング 販売', category: 'ビジネス' },
  { name: 'ネットマーケティング検定', alias: 'ねっとまーけてぃんぐ web マーケティング', category: 'ビジネス' },
  { name: 'ウェブ解析士', alias: 'うぇぶかいせきし web 解析 アクセス解析', category: 'ビジネス' },
  { name: 'ビジネス著作権検定', alias: 'ちょさくけん 著作権 知財 法律', category: 'ビジネス' },
  { name: 'ビジネスコンプライアンス検定', alias: 'こんぷらいあんす コンプライアンス 法令遵守', category: 'ビジネス' },
  { name: '法学検定試験', alias: 'ほうがく 法学 法律', category: 'ビジネス' },
  { name: '国際会計検定（BATIC）', alias: 'batic 国際会計 英文会計 会計', category: 'ビジネス' },
  { name: '全経簿記能力検定', alias: 'ぜんけい 全経 簿記 boki', category: 'ビジネス' },
  { name: '建設業経理士', alias: 'けんせつぎょうけいり 建設 経理 簿記', category: 'ビジネス' },
  { name: 'キャリアコンサルタント', alias: 'きゃりあこんさるたんt キャリア 相談', category: 'ビジネス', scoreType: 'pass' },
  { name: '衛生管理者（第二種）', alias: 'えいせいかんりしゃ 衛生 労働安全', category: 'ビジネス' },
  { name: '労働安全コンサルタント', alias: 'あんぜんこんさるたんt 労働安全 安全', category: 'ビジネス' },
  { name: '日商PC検定', alias: 'にっしょうぴーしー pc パソコン 日商', category: 'ビジネス' },
  { name: '文書デザイン検定', alias: 'ぶんしょでざいん 文書 デザイン', category: 'ビジネス' },
  { name: '日本語ワープロ検定', alias: 'わーぷろ ワープロ タイピング 文書', category: 'ビジネス' },
  { name: '速記技能検定', alias: 'そっき 速記 記録', category: 'ビジネス' },
  { name: '校正技能検定', alias: 'こうせい 校正 編集 出版', category: 'ビジネス' },
  { name: 'ホテル実務技能認定試験', alias: 'ほてる ホテル 宿泊 接客', category: 'ビジネス' },
  { name: 'ホテルビジネス実務検定（H検）', alias: 'hけん ホテル 宿泊 実務', category: 'ビジネス' },
  { name: '旅程管理主任者', alias: 'りょていかんり 添乗員 ツアコン 旅行', category: 'ビジネス' },
  { name: 'DIYアドバイザー', alias: 'diy でぃーあいわい 日曜大工', category: 'ビジネス' },
  { name: '調査士（与信管理士）', alias: 'よしん 与信 信用調査', category: 'ビジネス' },


  /* ---------- 語学（追加） ---------- */
  { name: '実用英語技能検定 3級', alias: '英検 えいけん eiken 3級 英語', category: '語学',
    scoreType: 'pass', url: 'https://www.eiken.or.jp/eiken/' },
  { name: 'GTEC', alias: 'gtec じーてっく 英語 ベネッセ', category: '語学' },
  { name: 'TEAP', alias: 'teap てぃーあっぷ 英語 大学入試', category: '語学' },
  { name: 'ケンブリッジ英語検定', alias: 'けんぶりっじ ケンブリッジ 英語 cambridge', category: '語学' },
  { name: '観光英語検定', alias: 'かんこうえいご 観光 英語 旅行', category: '語学' },
  { name: '国際連合公用語英語検定（国連英検）', alias: 'こくれんえいけん 国連 英語', category: '語学' },
  { name: '技術英語能力検定（技術英検）', alias: 'ぎじゅつえいご 技術英検 工業英検 英語', category: '語学' },
  { name: 'ビジネス通訳検定（TOBIS）', alias: 'つうやく 通訳 tobis 英語', category: '語学' },
  { name: 'ほんやく検定', alias: 'ほんやく 翻訳 translation 英語', category: '語学' },
  { name: '日商ビジネス英語検定', alias: 'びじねすえいご ビジネス英語 日商 英語', category: '語学' },
  { name: '全商英語検定', alias: 'ぜんしょうえいけん 英語 商業高校', category: '語学' },
  { name: '日本漢字能力検定 準1級', alias: 'kanken かんけん 漢検 漢字', category: '語学',
    scoreType: 'score', targetScore: 160, maxScore: 200, scoreUnit: '点',
    url: 'https://www.kanken.or.jp/kanken/', memo: '80%程度で合格。' },
  { name: '日本漢字能力検定 1級', alias: 'kanken かんけん 漢検 漢字', category: '語学',
    scoreType: 'score', targetScore: 160, maxScore: 200, scoreUnit: '点',
    url: 'https://www.kanken.or.jp/kanken/', memo: '80%程度で合格。' },
  { name: '日本漢字能力検定 3級', alias: 'kanken かんけん 漢検 漢字', category: '語学',
    scoreType: 'score', targetScore: 140, maxScore: 200, scoreUnit: '点',
    url: 'https://www.kanken.or.jp/kanken/', memo: '70%程度で合格。' },
  { name: '日本語検定（語検）', alias: 'にほんごけんてい 日本語 語検 国語', category: '語学' },
  { name: '文章読解・作成能力検定（文章検）', alias: 'ぶんしょうけん 文章 読解 作文', category: '語学' },
  { name: '語彙・読解力検定', alias: 'ごい 語彙 読解 国語', category: '語学' },
  { name: '日本語教育能力検定試験', alias: 'にほんごきょういく 日本語教師 教育', category: '語学' },
  { name: 'BJTビジネス日本語能力テスト', alias: 'bjt ビジネス日本語 日本語', category: '語学' },
  { name: '「ハングル」能力検定試験', alias: 'はんぐる ハングル 韓国語 ハン検', category: '語学' },
  { name: '実用イタリア語検定（伊検）', alias: 'いけん 伊検 イタリア語', category: '語学' },
  { name: 'DELE（スペイン語検定）', alias: 'dele スペイン語 でれ', category: '語学' },
  { name: 'スペイン語技能検定（西検）', alias: 'せいけん 西検 スペイン語', category: '語学' },
  { name: 'ロシア語能力検定（露検）', alias: 'ろけん 露検 ロシア語', category: '語学' },
  { name: '実用タイ語検定', alias: 'たいご タイ語 タイ', category: '語学' },
  { name: 'インドネシア語技能検定', alias: 'いんどねしあご インドネシア語', category: '語学' },
  { name: 'アラビア語検定', alias: 'あらびあご アラビア語', category: '語学' },
  { name: 'ベトナム語検定', alias: 'べとなむご ベトナム語', category: '語学' },
  { name: 'TOEFL ITP', alias: 'toefl itp 英語 団体', category: '語学' },
  { name: 'Versant スピーキングテスト', alias: 'versant ばーさんと 英語 スピーキング', category: '語学' },

  /* ---------- IT（追加） ---------- */
  { name: 'AWS認定 デベロッパー アソシエイト', alias: 'aws dva クラウド amazon 開発', category: 'IT' },
  { name: 'AWS認定 SysOpsアドミニストレーター アソシエイト', alias: 'aws soa クラウド amazon 運用', category: 'IT' },
  { name: 'AWS認定 ソリューションアーキテクト プロフェッショナル', alias: 'aws sap クラウド amazon', category: 'IT' },
  { name: 'Microsoft Azure Administrator (AZ-104)', alias: 'azure az104 クラウド マイクロソフト', category: 'IT' },
  { name: 'Google Cloud Professional Cloud Architect', alias: 'gcp google cloud pca クラウド', category: 'IT' },
  { name: 'CCNP Enterprise', alias: 'ccnp cisco シスコ ネットワーク', category: 'IT' },
  { name: 'LinuC レベル2', alias: 'linuc りなっく linux リナックス', category: 'IT' },
  { name: 'LPIC-2', alias: 'lpic linux リナックス', category: 'IT' },
  { name: 'Oracle Master Silver DBA', alias: 'oracle オラクル シルバー データベース', category: 'IT' },
  { name: 'OSS-DB技術者認定（Silver）', alias: 'ossdb postgresql データベース', category: 'IT' },
  { name: 'Java Silver（Oracle認定Javaプログラマ）', alias: 'java じゃば プログラミング oracle', category: 'IT' },
  { name: 'Python3 エンジニア認定データ分析試験', alias: 'python ぱいそん データ分析 pandas', category: 'IT' },
  { name: 'PHP技術者認定試験', alias: 'php ぴーえいちぴー プログラミング', category: 'IT' },
  { name: 'Ruby技術者認定試験', alias: 'ruby るびー プログラミング', category: 'IT' },
  { name: 'C言語プログラミング能力認定試験', alias: 'c言語 c プログラミング', category: 'IT' },
  { name: 'Javaプログラミング能力認定試験', alias: 'java じゃば プログラミング', category: 'IT' },
  { name: 'ジュニア・プログラミング検定', alias: 'じゅにあ プログラミング スクラッチ 子ども', category: 'IT' },
  { name: 'プログラミング能力検定（プロ検）', alias: 'ぷろけん プログラミング', category: 'IT' },
  { name: '日商プログラミング検定', alias: 'にっしょう プログラミング 日商', category: 'IT' },
  { name: 'AI検定', alias: 'ai えーあい 人工知能', category: 'IT' },
  { name: 'データサイエンティスト検定（DS検定）', alias: 'ds でーたさいえんてぃすと データ 分析', category: 'IT' },
  { name: 'Generative AI Test（JDLA）', alias: 'ai 生成ai jdla ジェネレーティブ', category: 'IT' },
  { name: '情報検定（J検）', alias: 'jけん 情報検定 情報', category: 'IT' },
  { name: '情報処理技術者能力認定試験', alias: 'じょうほうしょり 情報処理 認定', category: 'IT' },
  { name: '情報技術検定', alias: 'じょうほうぎじゅつ 情報 工業高校', category: 'IT' },
  { name: '情報処理検定（全商）', alias: 'ぜんしょう 情報処理 商業高校', category: 'IT' },
  { name: 'ICTプロフィシエンシー検定（P検）', alias: 'pけん パソコン検定 ict パソコン', category: 'IT' },
  { name: 'インターネット検定（.com Master）', alias: 'comマスター インターネット ntt', category: 'IT' },
  { name: '検索技術者検定', alias: 'けんさく 検索 情報検索', category: 'IT' },
  { name: 'MOS Word 一般（アソシエイト）', alias: 'mos word ワード マイクロソフト オフィス', category: 'IT' },
  { name: 'MOS Excel エキスパート', alias: 'mos excel エクセル エキスパート オフィス', category: 'IT' },
  { name: 'MOS PowerPoint', alias: 'mos powerpoint パワポ オフィス', category: 'IT' },
  { name: 'VBAエキスパート', alias: 'vba マクロ excel エクセル', category: 'IT' },
  { name: 'Excel表計算処理技能認定試験', alias: 'excel エクセル 表計算', category: 'IT' },
  { name: 'CAD利用技術者試験', alias: 'cad きゃど 製図 設計', category: 'IT' },
  { name: '3Dプリンター活用技術検定', alias: '3d プリンター 造形', category: 'IT' },
  { name: '情報セキュリティ管理士認定試験', alias: 'せきゅりてぃ セキュリティ 情報', category: 'IT' },
  { name: 'マイナンバー検定', alias: 'まいなんばー マイナンバー 個人情報', category: 'IT' },
  { name: 'ディジタル技術検定', alias: 'でじたる デジタル 技術 電子', category: 'IT' },
  { name: 'コンピュータサービス技能評価試験', alias: 'こんぴゅーた コンピュータ サービス', category: 'IT' },

  /* ---------- 技術・工業（追加） ---------- */
  { name: '危険物取扱者 乙種第1類', alias: 'きけんぶつ 乙1 危険物', category: '技術・工業' },
  { name: '危険物取扱者 甲種', alias: 'きけんぶつ 甲種 こうしゅ 危険物', category: '技術・工業' },
  { name: '危険物取扱者 丙種', alias: 'きけんぶつ 丙種 へいしゅ 危険物', category: '技術・工業' },
  { name: '消防設備士 甲種第4類', alias: 'しょうぼう 甲4 消防 火災報知', category: '技術・工業' },
  { name: '第二種電気主任技術者（電験二種）', alias: 'denken でんけん 電験二種 電気', category: '技術・工業' },
  { name: '第一種電気主任技術者（電験一種）', alias: 'denken でんけん 電験一種 電気', category: '技術・工業' },
  { name: '電気工事施工管理技士 2級', alias: 'せこうかんり 施工管理 電気', category: '技術・工業' },
  { name: '建築施工管理技士 2級', alias: 'せこうかんり 施工管理 建築', category: '技術・工業' },
  { name: '建築施工管理技士 1級', alias: 'せこうかんり 施工管理 建築', category: '技術・工業' },
  { name: '土木施工管理技士 2級', alias: 'せこうかんり 施工管理 土木 どぼく', category: '技術・工業' },
  { name: '土木施工管理技士 1級', alias: 'せこうかんり 施工管理 土木 どぼく', category: '技術・工業' },
  { name: '管工事施工管理技士 2級', alias: 'せこうかんり 施工管理 管工事 配管', category: '技術・工業' },
  { name: '造園施工管理技士', alias: 'せこうかんり 施工管理 造園', category: '技術・工業' },
  { name: '第二種冷凍機械責任者', alias: 'れいとう 冷凍 冷凍機械 高圧ガス', category: '技術・工業' },
  { name: '第三種冷凍機械責任者', alias: 'れいとう 冷凍 冷凍機械 高圧ガス', category: '技術・工業' },
  { name: '高圧ガス製造保安責任者（乙種機械）', alias: 'こうあつがす 高圧ガス 保安', category: '技術・工業' },
  { name: 'ボイラー技士 2級', alias: 'ぼいらー ボイラー 熱', category: '技術・工業' },
  { name: 'ガス溶接技能講習', alias: 'ようせつ 溶接 ガス', category: '技術・工業', scoreType: 'pass' },
  { name: 'アーク溶接特別教育', alias: 'ようせつ 溶接 アーク', category: '技術・工業', scoreType: 'pass' },
  { name: '玉掛け技能講習', alias: 'たまかけ 玉掛け クレーン', category: '技術・工業', scoreType: 'pass' },
  { name: 'フォークリフト運転技能講習', alias: 'ふぉーくりふと フォークリフト 荷役', category: '技術・工業', scoreType: 'pass' },
  { name: 'クレーン・デリック運転士', alias: 'くれーん クレーン 運転士', category: '技術・工業' },
  { name: '移動式クレーン運転士', alias: 'くれーん クレーン 移動式', category: '技術・工業' },
  { name: '第一級陸上特殊無線技士', alias: 'むせん 無線 一陸特 陸特', category: '技術・工業' },
  { name: '第三級陸上特殊無線技士', alias: 'むせん 無線 三陸特 陸特', category: '技術・工業' },
  { name: '工事担任者（第一級デジタル通信）', alias: 'こうじたんにんしゃ 工事担任者 通信', category: '技術・工業' },
  { name: '電気通信主任技術者', alias: 'でんきつうしん 電気通信 通信', category: '技術・工業' },
  { name: '機械保全技能士', alias: 'きかいほぜん 機械保全 保全', category: '技術・工業' },
  { name: '機械設計技術者試験', alias: 'きかいせっけい 機械設計 設計', category: '技術・工業' },
  { name: '技術士（第二次試験）', alias: 'ぎじゅつし 技術士 二次', category: '技術・工業' },
  { name: 'QC検定3級', alias: 'qc 品質管理 ひんしつ', category: '技術・工業' },
  { name: 'QC検定1級', alias: 'qc 品質管理 ひんしつ', category: '技術・工業' },
  { name: '危険物施設保安員', alias: 'きけんぶつ 保安 危険物', category: '技術・工業' },
  { name: '放射線取扱主任者', alias: 'ほうしゃせん 放射線 主任者', category: '技術・工業' },
  { name: 'エックス線作業主任者', alias: 'えっくすせん x線 放射線 作業主任者', category: '技術・工業' },
  { name: '公害防止管理者（水質関係）', alias: 'こうがい 公害 水質 環境', category: '技術・工業' },
  { name: '自動車整備士 2級', alias: 'せいびし 整備士 自動車 車', category: '技術・工業' },
  { name: '自動車検査員', alias: 'けんさいん 検査員 車検 自動車', category: '技術・工業' },

  /* ---------- 車・運転（追加） ---------- */
  { name: '準中型自動車免許', alias: 'じゅんちゅうがた 免許 車 運転', category: '車・運転', scoreType: 'pass' },
  { name: '中型自動車免許', alias: 'ちゅうがた 免許 車 運転 トラック', category: '車・運転', scoreType: 'pass' },
  { name: '大型自動車免許', alias: 'おおがた 免許 車 運転 トラック', category: '車・運転', scoreType: 'pass' },
  { name: '普通自動車第二種免許', alias: 'にしゅ 二種 免許 タクシー', category: '車・運転', scoreType: 'pass' },
  { name: '大型自動車第二種免許', alias: 'にしゅ 二種 免許 バス', category: '車・運転', scoreType: 'pass' },
  { name: '牽引免許', alias: 'けんいん 牽引 免許 トレーラー', category: '車・運転', scoreType: 'pass' },
  { name: '原動機付自転車免許（原付）', alias: 'げんつき 原付 免許 バイク', category: '車・運転', scoreType: 'pass' },
  { name: '小型特殊自動車免許', alias: 'こがたとくしゅ 免許 特殊', category: '車・運転', scoreType: 'pass' },
  { name: '大型特殊自動車免許', alias: 'おおがたとくしゅ 免許 特殊 重機', category: '車・運転', scoreType: 'pass' },
  { name: '運行管理者（旅客）', alias: 'うんこうかんりしゃ 運行管理 旅客 バス', category: '車・運転' },
  { name: '運行管理者（貨物）', alias: 'うんこうかんりしゃ 運行管理 貨物 トラック', category: '車・運転' },
  { name: '安全運転能力検定', alias: 'あんぜんうんてん 安全運転 車', category: '車・運転' },

  /* ---------- 不動産・建築（追加） ---------- */
  { name: '木造建築士', alias: 'もくぞう 建築士 木造', category: '不動産・建築' },
  { name: '不動産鑑定士', alias: 'かんていし 不動産鑑定 鑑定', category: '不動産・建築', scoreType: 'pass' },
  { name: '競売不動産取扱主任者', alias: 'けいばい 競売 不動産', category: '不動産・建築' },
  { name: '住宅ローンアドバイザー', alias: 'じゅうたくろーん 住宅ローン 不動産', category: '不動産・建築' },
  { name: '建築設備士', alias: 'けんちくせつび 建築設備 設備', category: '不動産・建築' },
  { name: '建築物環境衛生管理技術者（ビル管理士）', alias: 'びるかん ビル管理 建築物 衛生', category: '不動産・建築' },
  { name: '消防設備点検資格者', alias: 'しょうぼうせつび 消防設備 点検', category: '不動産・建築' },
  { name: '防火管理者', alias: 'ぼうかかんりしゃ 防火 消防', category: '不動産・建築', scoreType: 'pass' },

  /* ---------- 公務員・教育（追加） ---------- */
  { name: '国家公務員総合職試験', alias: 'こうむいん 公務員 国家総合職 キャリア', category: '公務員・教育', scoreType: 'pass' },
  { name: '国家公務員専門職試験', alias: 'こうむいん 公務員 専門職', category: '公務員・教育', scoreType: 'pass' },
  { name: '裁判所職員採用試験', alias: 'さいばんしょ 裁判所 公務員', category: '公務員・教育', scoreType: 'pass' },
  { name: '警察官採用試験', alias: 'けいさつ 警察官 公務員', category: '公務員・教育', scoreType: 'pass' },
  { name: '消防官採用試験', alias: 'しょうぼう 消防官 消防士 公務員', category: '公務員・教育', scoreType: 'pass' },
  { name: '市役所職員採用試験', alias: 'しやくしょ 市役所 公務員 地方', category: '公務員・教育', scoreType: 'pass' },
  { name: '小学校教諭免許状', alias: 'きょういん 教員免許 小学校 先生', category: '公務員・教育', scoreType: 'pass' },
  { name: '中学校教諭免許状', alias: 'きょういん 教員免許 中学校 先生', category: '公務員・教育', scoreType: 'pass' },
  { name: '高等学校教諭免許状', alias: 'きょういん 教員免許 高校 先生', category: '公務員・教育', scoreType: 'pass' },
  { name: '幼稚園教諭免許状', alias: 'きょういん 教員免許 幼稚園 先生', category: '公務員・教育', scoreType: 'pass' },
  { name: '司書（図書館司書）', alias: 'ししょ 司書 図書館', category: '公務員・教育', scoreType: 'pass' },
  { name: '社会教育主事', alias: 'しゃかいきょういく 社会教育 主事', category: '公務員・教育', scoreType: 'pass' },
  { name: '高等学校卒業程度認定試験（高認）', alias: 'こうにん 高卒認定 大検 高認', category: '公務員・教育', scoreType: 'pass' },
  { name: '公務適性検定', alias: 'こうむてきせい 公務 適性', category: '公務員・教育' },

];
